### ISSUE TITLE
百度云中的pdf都打不开

### ISSUE THREAD

**Issue by nachifur** [anzhihe/Free-Docker-Books#3]
大佬可以重新上传一下吗

**Comment by anzhihe** [comment]
链接可以打开，永久生效的，你用百度云客户端保存下载就行了

William Liu <notifications@github.com> 于2020年5月25日周一 下午10:08写道：

**Comment by anzhihe** [comment]
> 大佬可以重新上传一下吗

Google drive：https://drive.google.com/drive/folders/1Uh77UpNTCdh2paK-4KzdohGZ3e-9X1NE?usp=sharing

**Comment by nachifur** [comment]
谢谢大佬
